"""add event_type

Revision ID: ef5ed481bc11
Revises: 360ad8dd8a4e
Create Date: 2026-02-14 15:51:58.291017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5ed481bc11'
down_revision: Union[str, Sequence[str], None] = '360ad8dd8a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
